#!/bin/sh
#
# $FreeBSD: $
#

# PROVIDE: tekcoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# tekcoin_enable (bool):	Set to NO by default.
#				Set it to YES to enable tekcoin.
# tekcoin_config (path):	Set to /usr/local/etc/tekcoin.conf
#				by default.
# tekcoin_user:	The user account tekcoin daemon runs as
#				It uses 'root' user by default.
# tekcoin_group:	The group account tekcoin daemon runs as
#				It uses 'wheel' group by default.
# tekcoin_datadir (str):	Default to "/var/db/tekcoin"
#				Base data directory.

. /etc/rc.subr

name=tekcoin
rcvar=tekcoin_enable

: ${tekcoin_enable:=NO}
: ${tekcoin_config=/usr/local/etc/tekcoin.conf}
: ${tekcoin_datadir=/var/db/tekcoin}
: ${tekcoin_user="root"}
: ${tekcoin_group="wheel"}

required_files=${tekcoin_config}
command=/usr/local/bin/tekcoind
tekcoin_chdir=${tekcoin_datadir}
pidfile="${tekcoin_datadir}/tekcoind.pid"
stop_cmd=tekcoin_stop
command_args="-conf=${tekcoin_config} -datadir=${tekcoin_datadir} -noupnp -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

tekcoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${tekcoin_datadir}
	[ $? -eq 0 ] && chown -R ${tekcoin_user}:${tekcoin_group} ${tekcoin_datadir}
	#ln -s ${tekcoin_datadir} /.tekcoin
}

tekcoin_prestart()
{
	if [ ! -d "${tekcoin_datadir}/." ]; then
		tekcoin_create_datadir || return 1
	fi
}

tekcoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

tekcoin_stop()
{
    tekcoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${tekcoin_config} -datadir=${tekcoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
